SELECT B.INSTITUTION
 ,B.ACAD_CAREER
 ,B.ACAD_PROG
 ,TBL.DESCR
 ,TBL.ACAD_ORG
 ,ORG.DESCR
 ,B.ACAD_PLAN
 ,L.REQUIREMENT
 ,W.COURSE_LIST
 ,R.CRSE_ID
 ,L.DESCR
 ,E.DESCR
 ,R.INCLUDE_EQUIVALENT
 ,Q.RQ_GRP_LINE_NBR
 ,L.RQ_LINE_NBR
 ,W.RQ_LINE_DET_SEQ
 ,R.R_COURSE_SEQUENCE
 ,R1.LVF_TIPO_CURSO
 ,TT.LVF_CICLO_PLAN
 ,EE.CATALOG_NBR
 ,E.COURSE_TITLE_LONG
 ,E.UNITS_MAXIMUM
 ,EE.RQRMNT_GROUP
 ,' '
 ,' '
 ,' '
 ,' '
 ,' '
 ,' '
 ,' '
 ,' '
 ,' '
 ,' '
 ,' '
 ,' '
 ,' '
 ,' '
 ,' '
 ,' '
 ,E.EQUIV_CRSE_ID
 ,FF.WEEK_WORKLOAD_HRS
  FROM PS_RQ_GRP_TBL B
  ,PS_RQ_GRP_DETL_TBL Q
  ,PS_LVF_RQ_LINE_CIC TT
  , PS_RQ_MAIN_TBL T
  ,PS_RQ_LINE_TBL L
  ,PS_RQ_LN_DETL_TBL W
  ,PS_CLST_DETL_TBL R
  ,PS_LVF_TIP_CRSE_TB R1
  , PS_CLST_MAIN_TBL D
  ,PS_CRSE_CATALOG E
  ,PS_RQ_GRP_TBL B1
  ,PS_CRSE_OFFER EE
  ,%Table(CRSE_COMPONENT) FF
  ,PS_ACAD_PROG_TBL TBL
  ,PS_ACAD_ORG_TBL ORG
 WHERE T.EFFDT=(
 SELECT MAX(H.EFFDT)
  FROM PS_RQ_MAIN_TBL H
 WHERE H.REQUIREMENT=T.REQUIREMENT)
   AND T.EFF_STATUS='A'
   AND T.REQUIREMENT=L.REQUIREMENT
   AND T.EFFDT=L.EFFDT
   AND L.REQUIREMENT=W.REQUIREMENT
   AND L.EFFDT=W.EFFDT
   AND L.RQ_LINE_KEY_NBR=W.RQ_LINE_KEY_NBR
   AND W.RQ_LINE_DET_TYPE='CLST'
   AND R.EFFDT=(
 SELECT MAX(Z.EFFDT)
  FROM PS_CLST_DETL_TBL Z
 WHERE Z.COURSE_LIST=R.COURSE_LIST
   AND Z.EFFDT<=SYSDATE)
   AND R.COURSE_LIST=D.COURSE_LIST
   AND R.EFFDT=D.EFFDT
   AND D.EFF_STATUS='A'
   AND R.COURSE_LIST=W.COURSE_LIST
   AND B.EFFDT=(
 SELECT MAX(V.EFFDT)
  FROM PS_RQ_GRP_TBL V
 WHERE V.RQRMNT_GROUP=B.RQRMNT_GROUP
   AND V.EFFDT<=SYSDATE)
   AND B.EFF_STATUS='A'
   AND B.RQRMNT_USEAGE='ADV'
   AND B.RQRMNT_GROUP=Q.RQRMNT_GROUP
   AND B.EFFDT=Q.EFFDT
   AND Q.RQ_GRP_LINE_TYPE='RQ'
   AND Q.REQUIREMENT=T.REQUIREMENT
   AND %EffdtCheck(CRSE_CATALOG E1,E,%CURRENTDATEIN)
   AND %EffdtCheck(ACAD_PROG_TBL EE1,TBL,%CURRENTDATEIN)
   AND %EffdtCheck(ACAD_ORG_TBL EE2,ORG,%CURRENTDATEIN)
   AND ORG.ACAD_ORG=TBL.ACAD_ORG
   AND TBL.ACAD_PROG=B.ACAD_PROG
   AND TBL.INSTITUTION=B.INSTITUTION
   AND R.CRSE_ID=E.CRSE_ID
   AND R1.COURSE_LIST=R.COURSE_LIST
   AND R1.EFFDT=R.EFFDT
   AND R1.R_COURSE_SEQUENCE=R.R_COURSE_SEQUENCE
   AND TT.REQUIREMENT=L.REQUIREMENT
   AND TT.EFFDT=L.EFFDT
   AND TT.RQ_LINE_KEY_NBR=L.RQ_LINE_KEY_NBR
   AND E.CRSE_ID=EE.CRSE_ID
   AND E.EFFDT=EE.EFFDT
   AND B.RQRMNT_GROUP=B1.RQRMNT_GROUP
   AND B.EFFDT=B1.EFFDT
   AND EE.CRSE_ID=FF.CRSE_ID
   AND EE.EFFDT=FF.EFFDT
   AND FF.SSR_COMPONENT='LEC'
  ORDER BY Q.RQ_GRP_LINE_NBR ASC,L.RQ_LINE_NBR ASC , W.RQ_LINE_DET_SEQ ASC,R.R_COURSE_SEQUENCE ASC